# name: 워커 플로우 이름
# on:   브랜치명을 정의
# jobs: 실행할 작업을 정의
name: Nginx Deploy
on: 
  push:
    branches: ["main"]

jobs:
  deploy: # 배포정보
    runs-on: ubuntu-latest
    steps: 
      - name: 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: AWS 자격 증명 설정 S3에 배포
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: S3 버킷으로 파일 업로드
        run: |
          aws s3 sync html/ s3://github.kkhwan.cloud/ --delete
